// This file was generated by SquareLine Studio
// ENHANCED with dynamic GIF + comprehensive progress UI

#include "../ui.h"
#include <stdbool.h>

// ========================================================================
// FONT DECLARATIONS
// ========================================================================
extern const lv_font_t ui_font_InterSemiBold48;  // Main progress % / Tool Number
extern const lv_font_t ui_font_InterSemiBold20;  // ETA & Layer & Titles
extern const lv_font_t ui_font_InterSemiBold28;  // Tool indicator
extern const lv_font_t ui_font_InterSemiBold24;  // Temp Graph values
extern const lv_font_t ui_font_InterSemiBold16;  // Temp Graph titles (smaller)

// ========================================================================
// ASSETS
// ========================================================================
LV_IMG_DECLARE(ui_img_progress_ring);  // PNG ring overlay

// ========================================================================
// GLOBAL UI OBJECTS (Defined here, exported to other modules)
// ========================================================================
lv_obj_t * ui_ScreenPrinting = NULL;
lv_obj_t * ui_gif_print_progress_bg = NULL;
lv_obj_t * ui_arc_progress_cover = NULL;
lv_obj_t * ui_label_printing_progress = NULL;
lv_obj_t * ui_label_progress_eta = NULL;
lv_obj_t * ui_label_progress_layer = NULL;
lv_obj_t * ui_tool_bg_circle = NULL;
lv_obj_t * ui_label_tool_indicator = NULL;

// Accelerometer sliders (optional - if LIS2DW enabled)
lv_obj_t * ui_slider_printing_acc_x = NULL;
lv_obj_t * ui_label_printing_acc_x = NULL;
lv_obj_t * ui_slider_printing_acc_y = NULL;
lv_obj_t * ui_label_printing_acc_y = NULL;
lv_obj_t * ui_slider_printing_acc_z = NULL;
lv_obj_t * ui_label_printing_acc_z = NULL;

// NEW: Screen Rotation Views - Temp Graph Elements
lv_obj_t * ui_temp_chart = NULL;
lv_obj_t * ui_label_temp_title = NULL;
lv_obj_t * ui_label_temp_current = NULL;
lv_obj_t * ui_temp_bg_gif = NULL;  // animated BG for Temp Graph view (LittleFS GIF)

// NEW: Screen Rotation Views - Main Screen Animation
lv_obj_t * ui_main_screen_gif = NULL;

bool g_ui_progress_updates_enabled = true;  // default: enabled

// ========================================================================
// SCREEN INITIALIZATION
// ========================================================================
void ui_ScreenPrinting_screen_init(void)
{
    // Create screen if not exists
    if (!ui_ScreenPrinting) {
        ui_ScreenPrinting = lv_obj_create(NULL);
        lv_obj_clear_flag(ui_ScreenPrinting, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_set_style_bg_color(ui_ScreenPrinting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_ScreenPrinting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        
        // Event handler for gestures
        lv_obj_add_event_cb(ui_ScreenPrinting, ui_event_ScreenPrinting, LV_EVENT_ALL, NULL);
    }
    
    // ====================================================================
    // LAYER 0: Background GIF (rotating rim)
    // Created dynamically by lv_print_progress_update.cpp
    // ====================================================================
    
    // ====================================================================
    // LAYER 1: Static PNG Ring
    // ====================================================================
    if (!ui_gif_print_progress_bg) {
        ui_gif_print_progress_bg = lv_img_create(ui_ScreenPrinting);
        lv_img_set_src(ui_gif_print_progress_bg, &ui_img_progress_ring);
        lv_obj_set_size(ui_gif_print_progress_bg, 240, 240);
        lv_obj_center(ui_gif_print_progress_bg);
        lv_obj_move_to_index(ui_gif_print_progress_bg, 1);
    }
    
    // ====================================================================
    // LAYER 2: Cover Arc (SCHWARZ) - hides the "not yet done" part
    // ====================================================================
    if (!ui_arc_progress_cover) {
        ui_arc_progress_cover = lv_arc_create(ui_ScreenPrinting);
        lv_obj_set_size(ui_arc_progress_cover, 230, 230);  // ORIGINAL: 230x230 (thinner for outer animation)
        lv_obj_center(ui_arc_progress_cover);
        
        // Configure arc range and angles
        lv_arc_set_range(ui_arc_progress_cover, 0, 100);
        lv_arc_set_value(ui_arc_progress_cover, 0);
        
        // IMPORTANT: At 0% the arc must cover the entire circle
        // Start at 6 o'clock (270° + 180° = 450° in LVGL coords)
        // At 0%: 450° to 810° (full circle)
        // At 100%: 810° to 810° (no arc)
        lv_arc_set_angles(ui_arc_progress_cover, 450, 810);  // Start at 0% = full arc
        lv_arc_set_rotation(ui_arc_progress_cover, 0);
        
        // BLACK for final look - covers the "not yet done" part
        lv_obj_set_style_arc_color(ui_arc_progress_cover, lv_color_hex(0x000000), LV_PART_INDICATOR);
        lv_obj_set_style_arc_opa(ui_arc_progress_cover, 255, LV_PART_INDICATOR);
        lv_obj_set_style_arc_width(ui_arc_progress_cover, 26, LV_PART_INDICATOR);  // CRITICAL: 26px for full coverage of the colored ring
        lv_obj_set_style_arc_rounded(ui_arc_progress_cover, false, LV_PART_INDICATOR);
        
        // Hide background arc (we only use indicator)
        lv_obj_set_style_arc_opa(ui_arc_progress_cover, 0, LV_PART_MAIN);
        
        // Hide knob completely
        lv_obj_set_style_bg_opa(ui_arc_progress_cover, 0, LV_PART_KNOB);
        lv_obj_set_style_border_opa(ui_arc_progress_cover, 0, LV_PART_KNOB);
        lv_obj_set_style_pad_all(ui_arc_progress_cover, 0, LV_PART_KNOB);
        
        // No interaction
        lv_obj_clear_flag(ui_arc_progress_cover, LV_OBJ_FLAG_CLICKABLE);
        
        lv_obj_move_to_index(ui_arc_progress_cover, 2);
    }
    
    // ====================================================================
    // LAYER 3: Center Tool Glow Circle (EXAKT um Progress % in der Mitte)
    // ====================================================================
    if (!ui_tool_bg_circle) {
        ui_tool_bg_circle = lv_obj_create(ui_ScreenPrinting);
        lv_obj_set_size(ui_tool_bg_circle, 120, 120);  // Larger for better glow around progress
        lv_obj_align(ui_tool_bg_circle, LV_ALIGN_CENTER, 0, 0);  // EXAKT in der Mitte!
        lv_obj_set_style_radius(ui_tool_bg_circle, LV_RADIUS_CIRCLE, 0);
        
        // Transparent, only glow via shadow
        lv_obj_set_style_bg_opa(ui_tool_bg_circle, LV_OPA_0, 0);
        lv_obj_set_style_border_opa(ui_tool_bg_circle, LV_OPA_0, 0);
        
        // START mit sehr starkem Glow - maximale Sichtbarkeit!
        lv_obj_set_style_shadow_width(ui_tool_bg_circle, 24, 0);   // dezenter Glow
        lv_obj_set_style_shadow_color(ui_tool_bg_circle, lv_color_hex(0x00FFFF), 0);  // Cyan
        lv_obj_set_style_shadow_opa(ui_tool_bg_circle, 140, 0);    // geringere Deckkraft
        lv_obj_set_style_shadow_spread(ui_tool_bg_circle, 6, 0);   // kleinerer Spread
        lv_obj_move_background(ui_tool_bg_circle);                 // hinter die Labels
        
        lv_obj_move_to_index(ui_tool_bg_circle, 3);
    }
    
    // ====================================================================
    // LAYER 4: Tool Indicator Label (Temperatur - konstant sichtbar)
    // ====================================================================
    if (!ui_label_tool_indicator) {
        ui_label_tool_indicator = lv_label_create(ui_ScreenPrinting);
        lv_label_set_text(ui_label_tool_indicator, "260°C");  // Platzhalter
        lv_obj_set_style_text_color(ui_label_tool_indicator, lv_color_white(), 0);
        lv_obj_set_style_text_font(ui_label_tool_indicator, &ui_font_InterSemiBold28, 0);
        lv_obj_set_style_text_align(ui_label_tool_indicator, LV_TEXT_ALIGN_CENTER, 0);
        
        // Position besser lesbar - weiter unten
        lv_obj_align(ui_label_tool_indicator, LV_ALIGN_TOP_MID, 0, 55);
        
        // Shadow for better readability
        lv_obj_set_style_shadow_width(ui_label_tool_indicator, 8, 0);
        lv_obj_set_style_shadow_color(ui_label_tool_indicator, lv_color_black(), 0);
        lv_obj_set_style_shadow_opa(ui_label_tool_indicator, LV_OPA_80, 0);
        lv_obj_move_foreground(ui_label_tool_indicator);
    }
    
    // ====================================================================
    // LAYER 5: Main Progress % Label (CENTER - LARGE)
    // ====================================================================
    if (!ui_label_printing_progress) {
        ui_label_printing_progress = lv_label_create(ui_ScreenPrinting);
        lv_label_set_text(ui_label_printing_progress, "0%");
        lv_obj_set_style_text_color(ui_label_printing_progress, lv_color_white(), 0);
        lv_obj_set_style_text_font(ui_label_printing_progress, &ui_font_InterSemiBold48, 0);
        lv_obj_set_style_text_align(ui_label_printing_progress, LV_TEXT_ALIGN_CENTER, 0);
        
        // Position at center
        lv_obj_center(ui_label_printing_progress);
        
        // Add strong shadow for better readability
        lv_obj_set_style_shadow_width(ui_label_printing_progress, 12, 0);
        lv_obj_set_style_shadow_color(ui_label_printing_progress, lv_color_black(), 0);
        lv_obj_set_style_shadow_opa(ui_label_printing_progress, 200, 0);
        lv_obj_set_style_shadow_spread(ui_label_printing_progress, 3, 0);
        
        lv_obj_move_to_index(ui_label_printing_progress, 10);
        lv_obj_move_foreground(ui_label_printing_progress);
    }
    
    // ====================================================================
    // LAYER 6: ETA Label (Time Remaining)
    // ====================================================================
    if (!ui_label_progress_eta) {
        ui_label_progress_eta = lv_label_create(ui_ScreenPrinting);
        lv_label_set_text(ui_label_progress_eta, "Calculating...");
        lv_obj_set_style_text_color(ui_label_progress_eta, lv_color_hex(0xFFFFFF), 0);
        lv_obj_set_style_text_font(ui_label_progress_eta, &ui_font_InterSemiBold20, 0);
        lv_obj_set_style_text_align(ui_label_progress_eta, LV_TEXT_ALIGN_CENTER, 0);
        
        // Position bottom-center, above layer label
        lv_obj_align(ui_label_progress_eta, LV_ALIGN_BOTTOM_MID, 0, -30);
        
        lv_obj_move_to_index(ui_label_progress_eta, 11);
        lv_obj_move_foreground(ui_label_progress_eta);
    }
    
    // ====================================================================
    // LAYER 7: Layer Info Label
    // ====================================================================
    if (!ui_label_progress_layer) {
        ui_label_progress_layer = lv_label_create(ui_ScreenPrinting);
        lv_label_set_text(ui_label_progress_layer, "Layer 0/0");
        lv_obj_set_style_text_color(ui_label_progress_layer, lv_color_hex(0xCCCCCC), 0);
        lv_obj_set_style_text_font(ui_label_progress_layer, &ui_font_InterSemiBold20, 0);
        lv_obj_set_style_text_align(ui_label_progress_layer, LV_TEXT_ALIGN_CENTER, 0);
        
        // Position unter Progress % Label
        lv_obj_align(ui_label_progress_layer, LV_ALIGN_CENTER, 0, 50);
        
        lv_obj_move_to_index(ui_label_progress_layer, 12);
        lv_obj_move_foreground(ui_label_progress_layer);
    }
    
    // ====================================================================
    // Optional: Accelerometer UI (if LIS2DW12 enabled)
    // Not created here - keep NULL if not needed
    // ====================================================================
    
    // ====================================================================
    // LAYER 8: Temp Graph View Elements (initially hidden)
    // ====================================================================
#if LV_USE_GIF
    if (!ui_temp_bg_gif) {
        ui_temp_bg_gif = lv_gif_create(ui_ScreenPrinting);
        lv_obj_set_size(ui_temp_bg_gif, 240, 240);
        lv_obj_center(ui_temp_bg_gif);
        // NOTE: adjust drive letter if your LittleFS letter differs from 'L'
        lv_gif_set_src(ui_temp_bg_gif, "L:/gifs/print_progress_bg.gif");
        lv_obj_add_flag(ui_temp_bg_gif, LV_OBJ_FLAG_HIDDEN);  // initially hidden
        lv_obj_move_to_index(ui_temp_bg_gif, 0);              // very back
    }
#endif

    if (!ui_label_temp_title) {
        ui_label_temp_title = lv_label_create(ui_ScreenPrinting);
        lv_label_set_text(ui_label_temp_title, "Nozzle Temperature");
        lv_obj_set_style_text_color(ui_label_temp_title, lv_color_hex(0xFFFFFF), 0);
        lv_obj_set_style_text_font(ui_label_temp_title, &ui_font_InterSemiBold16, 0);  // Kleiner: 16 statt 20
        lv_obj_set_style_text_align(ui_label_temp_title, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_align(ui_label_temp_title, LV_ALIGN_CENTER, 0, -60);  // Tiefer: -60 statt -70
        lv_obj_add_flag(ui_label_temp_title, LV_OBJ_FLAG_HIDDEN);  // Initially hidden
        lv_obj_move_foreground(ui_label_temp_title);
    }
    
    if (!ui_temp_chart) {
        ui_temp_chart = lv_chart_create(ui_ScreenPrinting);
        lv_obj_set_size(ui_temp_chart, 180, 100);
        lv_obj_center(ui_temp_chart);
        lv_obj_set_style_bg_color(ui_temp_chart, lv_color_hex(0x000000), 0);
        lv_obj_set_style_bg_opa(ui_temp_chart, LV_OPA_COVER, 0);
        lv_obj_set_style_border_width(ui_temp_chart, 0, 0);
        lv_obj_set_style_radius(ui_temp_chart, 8, 0);
        
        // Chart configuration
        lv_chart_set_type(ui_temp_chart, LV_CHART_TYPE_LINE);
        lv_chart_set_range(ui_temp_chart, LV_CHART_AXIS_PRIMARY_Y, 0, 300);
        lv_chart_set_point_count(ui_temp_chart, 60);  // 60 seconds history
        lv_chart_set_div_line_count(ui_temp_chart, 5, 5);
        
        // Style for the line
        lv_obj_set_style_line_width(ui_temp_chart, 3, LV_PART_ITEMS);
        lv_obj_set_style_line_rounded(ui_temp_chart, true, LV_PART_ITEMS);
        
        // Grid lines style
        lv_obj_set_style_line_color(ui_temp_chart, lv_color_hex(0x333333), LV_PART_MAIN);
        lv_obj_set_style_line_width(ui_temp_chart, 1, LV_PART_MAIN);
        
        // Add data series with Neon Green color
        lv_chart_series_t * ser = lv_chart_add_series(ui_temp_chart, lv_color_hex(0x00FF00), LV_CHART_AXIS_PRIMARY_Y);
        
        lv_obj_add_flag(ui_temp_chart, LV_OBJ_FLAG_HIDDEN);  // Initially hidden
        lv_obj_move_foreground(ui_temp_chart);
    }
    
    if (!ui_label_temp_current) {
        ui_label_temp_current = lv_label_create(ui_ScreenPrinting);
        lv_label_set_text(ui_label_temp_current, "Current: 0°C");
        lv_obj_set_style_text_color(ui_label_temp_current, lv_color_hex(0xFFFFFF), 0);
        lv_obj_set_style_text_font(ui_label_temp_current, &ui_font_InterSemiBold16, 0);  // Kleiner: 16 statt 20
        lv_obj_set_style_text_align(ui_label_temp_current, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_align(ui_label_temp_current, LV_ALIGN_CENTER, 0, 70);
        lv_obj_add_flag(ui_label_temp_current, LV_OBJ_FLAG_HIDDEN);  // Initially hidden
        lv_obj_move_foreground(ui_label_temp_current);
    }
    
    // ====================================================================
    // LAYER 9: Main Screen Animation (initially hidden)
    // Created dynamically by lv_print_progress_update.cpp when needed
    // GIF will be loaded from /gifs/tool_X.gif based on active tool
    // ====================================================================
    // ui_main_screen_gif is created on-demand in update function
}
